=== jeffyjahfar/uml-to-sparql-converter/src/com/uw/css/utils/xmitrans.dtd
<!ELEMENT xmitransformations ( xmitransformation+ ) >
<!ATTLIST xmitransformations
	 version CDATA #REQUIRED
	 requirexmiid (true|false) "true">

<!ELEMENT xmitransformation (trigger*) >
<!ATTLIST xmitransformation
	 modelelement CDATA #REQUIRED
	 xmipattern CDATA #REQUIRED
	 recurse (true|false) "false"
	 requirexmiid (true|false) #IMPLIED
	 condition CDATA #IMPLIED>

<!ELEMENT trigger EMPTY>
<!ATTLIST trigger
	 name CDATA #REQUIRED
	 type (attrval|cattrval|gcattrval|ctext|reflist|constant|ignore|xmi2assoc) #REQUIRED
	 attr CDATA #IMPLIED
	 src CDATA #IMPLIED
	 linkbackattr CDATA #IMPLIED>

=== jeffyjahfar/uml-to-sparql-converter/test/metamodels/testXMITransformations05.xml
<?xml version="1.0"?>
<!DOCTYPE xmitransformations SYSTEM 'xmitrans.dtd'>

<xmitransformations version="2.0">

<xmitransformation modelelement="sdmetricsbase" xmipattern="sdmetricsbase" recurse="true">
<trigger name="id" type="attrval" attr="xmi:id" />
<trigger name="name" type="attrval" attr="name" />
</xmitransformation>

<xmitransformation modelelement="interaction" xmipattern="uml:Interaction" recurse="true">
	<trigger name="lifelines" type="xmi2assoc" src="uml:Lifeline" attr="lifeline" />
	<trigger name="messages" type="xmi2assoc" src="uml:Message" attr="message" />
	<trigger name="fragments" type="xmi2assoc" attr="fragment" />
</xmitransformation>

<xmitransformation modelelement="lifeline" xmipattern="uml:Lifeline">
	<trigger name="coveredBy" type="xmi2assoc" attr="coveredBy" />
	<trigger name="represents" type="xmi2assoc" attr="represents" />
</xmitransformation>

<xmitransformation modelelement="occurrencespec" xmipattern="uml:MessageOccurrenceSpecification">
	<trigger name="covered" type="xmi2assoc" attr="covered" />
	<trigger name="event" type="xmi2assoc" attr="event" />
</xmitransformation>

<xmitransformation modelelement="package" xmipattern="uml:Package" recurse="true" />
<xmitransformation modelelement="model" xmipattern="uml:Model" recurse="true" />

</xmitransformations>

=== jeffyjahfar/uml-to-sparql-converter/test/metamodels/testXMITransformations06.xml
<?xml version="1.0"?>
<!DOCTYPE xmitransformations SYSTEM 'xmitrans.dtd'>

<xmitransformations version="2.0">

<xmitransformation modelelement="sdmetricsbase" xmipattern="sdmetricsbase" recurse="true">
<trigger name="id" type="attrval" attr="xmi.id" />
<trigger name="name" type="attrval" attr="name" />
<trigger name="context" type="attrval" attr="namespace"/>
<trigger name="stapplication" type="reflist" attr="xmi.idref" src="UML:ModelElement.stereotype" />
</xmitransformation>

<xmitransformation modelelement="class" xmipattern="UML:Class" recurse="true" />

<xmitransformation modelelement="stereotype" xmipattern="UML:Stereotype" />

</xmitransformations>

=== jeffyjahfar/uml-to-sparql-converter/test/metamodels/testXMITransformations04.xml
<?xml version="1.0"?>
<!DOCTYPE xmitransformations SYSTEM 'xmitrans.dtd'>

<xmitransformations version="2.0">


<xmitransformation modelelement="sdmetricsbase" xmipattern="sdmetricsbase" recurse="true">
<trigger name="id" type="attrval" attr="xmi.id" />
<trigger name="name" type="attrval" attr="name" />
<trigger name="name" type="ctext" src="UML:ModelElement.name" />
<trigger name="context" type="attrval" attr="namespace"/>
<trigger name="context" type="gcattrval" src="UML:ModelElement.namespace" attr="xmi.idref"/>
<trigger name="stereotypes" type="gcattrval" src="UML:ModelElement.stereotype"
				 attr="xmi.idref" linkbackattr="extendedelements" />
</xmitransformation>

<xmitransformation modelelement="class" xmipattern="UML:Class" recurse="true">
<trigger name="visibility" type="cattrval" src="UML:ModelElement.visibility" attr="xmi.value"/>
<trigger name="visibility" type="attrval" attr="visibility" />
</xmitransformation>


<xmitransformation modelelement="attribute" xmipattern="UML:Attribute" recurse="true">
<trigger name="id" type="ignore" />
<trigger name="visibility" type="attrval" attr="visibility" />
<trigger name="visibility" type="cattrval" src="UML:ModelElement.visibility" attr="xmi.value"/>
<trigger name="context" type="attrval" attr="owner"/>
<trigger name="context" type="gcattrval" src="UML:Feature.owner" attr="xmi.idref"/>

</xmitransformation>

<xmitransformation modelelement="operation" xmipattern="UML:Operation" recurse="true">
<trigger name="name" type="constant" attr="Halibut" />
<trigger name="visibility" type="attrval" attr="visibility"/>
<trigger name="visibility" type="cattrval" src="UML:ModelElement.visibility" attr="xmi.value"/>
<trigger name="context" type="attrval" attr="owner"/>
<trigger name="context" type="gcattrval" src="UML:ModelElement.namespace" attr="xmi.idref"/>
</xmitransformation>

<xmitransformation modelelement="generalization" xmipattern="UML:Generalization" >
<trigger name="genchild" type="gcattrval" src="UML:Generalization.child" attr="xmi.idref" linkbackattr="nosuchattribute"/>
<trigger name="genchild" type="attrval" attr="child" />
<trigger name="genparent" type="gcattrval" src="UML:Generalization.parent" attr="xmi.idref"/>
<trigger name="genparent" type="attrval" attr="parent"/>
</xmitransformation>

<xmitransformation modelelement="stereotype" xmipattern="UML:Stereotype" requirexmiid="false">
	<trigger name="extendedelements" type="gcattrval" src="UML:Stereotype.extendedElement"
		attr="xmi.idref" linkbackattr="stereotypes" />
</xmitransformation>

<xmitransformation modelelement="taggedvalue" xmipattern="UML:TaggedValue" requirexmiid="false">
<trigger name="value" type="ctext" src="UML:TaggedValue.dataValue" />
<trigger name="definition" type="attrval" attr="type" />
<trigger name="definition" type="gcattrval" src="UML:TaggedValue.type" attr="xmi.idref" />
<trigger name="context" type="attrval" attr="modelElement" />
<trigger name="context" type="gcattrval" src="UML:TaggedValue.modelElement" attr="xmi.idref" />
</xmitransformation>

<xmitransformation modelelement="model" xmipattern="UML:Model" recurse="true">
<trigger name="context" type="ignore"/>
</xmitransformation>

<xmitransformation modelelement="package" xmipattern="UML:Package" recurse="true">
</xmitransformation>


<xmitransformation modelelement="lightextension" xmipattern="ext:light">
<trigger name="baseclass" type="attrval" attr="base" />
<trigger name="extval" type="attrval" attr="value" />
</xmitransformation>

<xmitransformation modelelement="fullextension" xmipattern="ext:heavy">
<trigger name="baseclass" type="attrval" attr="base" />
<trigger name="extval" type="attrval" attr="value" />
</xmitransformation>

<xmitransformation modelelement="derivedfullextension" xmipattern="ext:derived">
<trigger name="derivedextval" type="attrval" attr="value2" />
</xmitransformation>

</xmitransformations>

=== jeffyjahfar/uml-to-sparql-converter/test/metamodels/testXMITransformations07.xml
<?xml version="1.0"?>
<!DOCTYPE xmitransformations SYSTEM 'xmitrans.dtd'>

<xmitransformations version="2.0">

<xmitransformation modelelement="sdmetricsbase" xmipattern="sdmetricsbase" recurse="true">
<trigger name="id" type="attrval" attr="xmi:id" />
<trigger name="name" type="attrval" attr="name" />
</xmitransformation>

<xmitransformation modelelement="model" xmipattern="uml:Model" recurse="true" />
<xmitransformation modelelement="package" xmipattern="uml:Package" recurse="true" />

<xmitransformation modelelement="eaextensionelement" xmipattern="element" requirexmiid="false" allowxmiidref="true" recurse="false" condition="geometry=''">
	<trigger name="elemref" type="attrval" attr="xmi:idref" />
	<trigger name="name" type="attrval" attr="name" />
	<trigger name="documentation" type="cattrval" attr="documentation" src="properties" />
	<trigger name="author" type="cattrval" attr="author" src="project" />
</xmitransformation>

</xmitransformations>
